version: '3.8'

services:
  angular-app:
    build:
      context: ./testeAngular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./testeAngular:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  laravel-app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
